name: Jekyll site CI

on:
  push:
    branches: [ "master", "action/release/4.1-action-speedup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Define cache key
        id: vars
        run: echo "key=v1md-${{ runner.os }}-jekyll-${{ github.ref }}-${{ env.HASH }}" >> $GITHUB_OUTPUT
        env:
          HASH: ${{ hashFiles('**/*') }}
    
      # Step 1: Restore cache
      - name: Restore Jekyll cache
        id: cache-jekyll
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.jekyll-metadata
            ${{ github.workspace }}/_site
          key: ${{ steps.vars.outputs.key }}
          restore-keys: |
            v1md-${{ runner.os }}-jekyll-${{ github.ref }}
            v1md-${{ runner.os }}-jekyll-

      # - run: mkdir -p ${{ github.workspace }}/.jekyll-cache
      # - run: chmod -R 777 ${{ github.workspace }}/.jekyll-cache
      # - run: ls -lah ${{ github.workspace }}/.jekyll-cache
      
      - run: ls -lah ${{ github.workspace }}/.jekyll-metadata || true
      
      - run: echo "::debug::workspace is ${{ github.workspace }}"
      - run: ls -lah ${{ github.workspace }}
      - run: chmod -R 777 ${{ github.workspace }}
      # - run: ls -lah ${{ github.workspace }}
      # - run: whoami
      - run: printenv
      
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -e "PAGES_REPO_NWO=${{ github.repository }}" \
          jekyll/builder:latest /bin/bash -c "whoami && jekyll -v && jekyll build"

      # - run: ls -lah ${{ github.workspace }}/.jekyll-cache
      # - run: chmod -R 777 ${{ github.workspace }}/.jekyll-cache
      # - run: ls -lah ${{ github.workspace }}/.jekyll-cache

      - run: ls -lah ${{ github.workspace }}/.jekyll-metadata || true
      
      - name: Save branch-specific Jekyll cache
        if: steps.cache-jekyll.outputs.cache-hit != 'true' || steps.vars.outputs.key != steps.cache-jekyll.outputs.cache-matched-key
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/.jekyll-metadata
            ${{ github.workspace }}/_site
          key: ${{ steps.vars.outputs.key }}
