name: Jekyll site CI

on:
  push:
    branches: [ "master", "action/release/4.1-action-speedup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - run: echo "::debug::workspace is ${{ github.workspace }}"
    # - run: echo "::debug::pwd is $(pwd)"
    - run: ls -lah ${{ github.workspace }}
    # - run: chmod -R 777 ${{ github.workspace }}
    # - run: ls -lah ${{ github.workspace }}
    - run: whoami
    - run: jekyll build
