name: Jekyll site CI

on:
  push:
    branches: [ "master", "action/release/4.1-action-speedup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - run: echo "::debug::workspace is ${{ github.workspace }}"
    - run: echo "::debug::pwd is $(pwd)"
    - run: ls -lah ${{ github.workspace }}
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        -e "PAGES_REPO_NWO=${{ github.repository }}" \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
